# Generated by Django 4.1.1 on 2022-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
    ]
